language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - name: PHP 7.0 with Magento 2.2.0
      php: 7.0
      env: MAGENTO_VERSION=2.2.0 MAGE_MODE=default
    - name: PHP 7.2 with Magento 2.2.10
      php: 7.2
      env: MAGENTO_VERSION=2.2.10 MAGE_MODE=production
    - name: PHP 7.1 with Magento 2.3.1
      php: 7.1
      env: MAGENTO_VERSION=2.3.1 MAGE_MODE=developer
    - name: PHP 7.3 with Magento 2.3.3
      php: 7.3
      env: MAGENTO_VERSION=2.3.3 MAGE_MODE=production

mysql:
  database: extdn_installer_db
  username: root

before_install:
  - composer --verbose self-update
  - composer --version

before_script:
  - mysql -e 'create database extdn_installer_db'

script:
  # Run automated tests.
  - composer create-project --repository=https://repo-magento-mirror.fooman.co.nz/ magento/project-community-edition=$MAGENTO_VERSION m2-folder --no-install --no-interaction
  - cd m2-folder
  - composer config --unset repo.0
  - composer config repo.foomanmirror composer https://repo-magento-mirror.fooman.co.nz/
  - composer install --prefer-dist
  - php -f bin/magento setup:install --db-host=localhost --db-user=root --db-name=extdn_installer_db --admin-user=admin --admin-password=admin123 --admin-email="test@example.com" --admin-firstname=Test --admin-lastname=Admin --backend-frontname=admin
  - if [ $MAGE_MODE != "default" ]; then php -f bin/magento deploy:mode:set $MAGE_MODE; fi
  # test a oneliner installation from packagist
  - sh -ic "$(curl -sS https://raw.githubusercontent.com/extdn/installer-m2/master/bin/oneliner.sh)" -- --no-interaction install fooman/printorderpdf-m2:^3.0
  # test a oneliner installation from github
  - composer config use-github-api false
  - sh -ic "$(curl -sS https://raw.githubusercontent.com/extdn/installer-m2/master/bin/oneliner.sh)"  -- --template=github --repo-url=https://github.com/fooman/emailattachments-m2.git --no-interaction install fooman/emailattachments-m2:^3.0